"""
Protocol for PM flow actions

Abstracts concrete UI interactions needed by PM flow.
"""
from __future__ import annotations
from typing import Protocol, runtime_checkable, Dict, Any, Optional


@runtime_checkable
class PmActions(Protocol):
    def get_lighthouse_status(self, mva: str) -> Optional[str]: ...
    def has_open_workitem(self, mva: str) -> bool: ...
    def complete_open_workitem(self, mva: str) -> Dict[str, Any]: ...
    def has_pm_complaint(self, mva: str) -> bool: ...
    def associate_pm_complaint(self, mva: str) -> Dict[str, Any]: ...
    def navigate_back_home(self) -> None: ...
    def find_workitem(self, mva: str, damage_type: str, sub_damage_type: str, correction_action: str) -> Optional[Dict[str, Any]]: ...
    def create_workitem(self, mva: str, damage_type: str, sub_damage_type: str, correction_action: str) -> Dict[str, Any]: ...
